name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
